version: '3.9'

services:
  client:
    build:
      context: ./client
    user: nextjs
    command: npm run start
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
  server:
    build:
      context: ./server
    command: java -cp target/Server-1.0-SNAPSHOT.jar dev.liobr.randyscandies.Main
    ports:
      - 4567:4567
    environment:
      JAVA_ENV: production
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/var/www/certbot/:/var/www/certbot/:ro
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - client
      - server
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/var/www/certbot/:/var/www/certbot/:rw
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/var/log/letsencrypt/:/var/log/letsencrypt/:rw
